config/routes.rb
Foto::Application.routes.draw do


  resources :tags

  devise_for :users
  
  get "welcome/index"
  get "profile"       => "profiles#user_profile", :as => :user_profile
  get "profile/edit"  => "profiles#edit",         :as => :edit_user_profile
  post"profile/edit"  => "profiles#update"
  get "profiles/:id"  => "profiles#show"
  put "profile"       => "profiles#update"
  
  get "/users/:username" => "profiles#show",       :as => :username_profile
  resources :users do
    resources :pictures
    resources :feedbacks
  end
  
  resources :pictures do
    resources :feedbacks
  end

  match "/pictures/tags/:tag"       => "pictures#tags", :as => :tagged_with
  match "/feedbacks/"               => "feedbacks#index"
  match "/feedbacks/:id/upvote"     => "feedbacks#upvote", :as => :feedback_upvote
  match "/feedbacks/:id/downvote"   => "feedbacks#downvote", :as => :feedback_downvote

  root :to => "welcome#index"
end

app/models/picture.rb
class Picture
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :desc
  field :name
  field :username

  field :tags,    :type => Array,   :default => []
  field :private, :type => Boolean, :default => false
 
  field :voters,  :type => Array
  field :votes,   :type => Integer, :default => 0

  field :views,   :type => Integer, :default => 0
  field :viewers, :type => Array
  
  mount_uploader :pic, PictureImageProcessor  
 
  # references_many :tags,      :stored_as => :array
  references_many :feedbacks

  referenced_in :user
  
  
  validates_presence_of :name
  validates_presence_of :username

  def user=(u)
    self.user_id  = u.id
    self.username = u.username
  end

  class << self
    def public 
      where(:private => false)
    end
    
    def ordered
      desc(:created_at)
    end
    
    def by_page(page)
      limit(6).skip(page ? page.to_i * 6 : 0)
    end
    
    def find_by_user_id(user_id)
      where(:user_id => user_id)
    end
   
    def vote(story_id, user_id, direction)
      story_id = BSON::ObjectId(story_id) if story_id.class == String
      user_id  = BSON::ObjectId(user_id) if user_id == String

      collection.update({'_id' => story_id, 'voters' => {'$ne' => user_id}}, 
        {'$inc' => {'votes' => direction}, '$push' => {'voters' => user_id}})
    end

    def downvote(story_id, user_id)
      self.vote(story_id, user_id, -1)
    end

    def upvote(story_id, user_id)
      self.vote(story_id, user_id, 1)
    end

    def remove_tag(tag)
      collection.update(
        { 'tags'  => { '$in'  => [tag] }},
        { '$pull' => { 'tags' =>  tag  }}, {:multi => true})
    end
  end

  def tags_s 
    self.tags.map(&:name).join(", ") if self.tags
  end

  def tags_s=(ts)
    self.tags = []
    ts.split(",").each do |tag|
      tag = tag.downcase.strip
      self.tags << tag unless self.tags.include? tag
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!,      :except => [:show, :index, :tags]
  before_filter :find_picture_by_id,      :only   => [:show, :edit, :update, :destroy]
  before_filter :authenticate_ownership!, :only   => [:edit, :update, :destroy]

  respond_to :html, :js

  def index
    if params[:user_id]
      @pictures = Picture.find_by_user_id(params[:user_id])
    else
      @pictures = Picture
    end

    @pictures = @pictures.public.ordered.by_page(params[:page])

    respond_with(@pictures)
  end

  def show
    if @picture.private && !owner?
      render :layout  => false, 
             :file    => "#{Rails.root}/public/404.html",
             :status  => 404 and return
    end
  end
  
  def tags
    @pictures = []
    if params[:tag]
      @pictures = Picture.public.ordered.where(:tags.in => [params[:tag]])
    end

    render :index
  end

  def upvote 
    @picture = Picture.find(params[:picture_id])

    Picture.upvote(params[:picture_id], current_user.id)
    render :show
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = Picture.new(params[:picture])
    @picture.user = current_user

   if @picture.save
     redirect_to(@picture, :notice => 'Picture was successfully created.')
   else
     render :action => "new" 
   end
  end

  def update
    if @picture.update_attributes(params[:picture])
      redirect_to(@picture, :notice => 'Picture was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @picture.destroy

    redirect_to(pictures_url, :notice => 'Picture was successfully deleted.')
  end
  
  private
  
  def find_picture_by_id
    @picture = Picture.find(params[:id])
  end
  
  def authenticate_ownership!
    unless owner?
      redirect_to(user_profile_path, :alert => "You can not do such things!")
    end
  end
  
  def owner?
    (@picture && current_user && @picture.user == current_user)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :pic %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <span class="help"> The title of the image </span>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <% Tag.all.each do |tag| %>
      <%= check_box_tag "picture[tags][]", tag.id, @picture.tags.include?(tag.name) %> 
      <%= tag.name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
    <span class="help"> A short description of what this is and what kind of feedback you are looking for. </span>
  </div>
  <div class="field">
    <%= f.label :private %>:
    <%= f.check_box :private %>
    <span class="help"> If private is checked this picture is only visible to you.</span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div class="picture clearfix">
  <div class="thumb">
    <%= link_to image_tag(picture.pic.thumb.url), picture %>
  </div>
  <div class="name">
    <%= link_to picture.name, picture %>
  </div>
  <p class="description">
    <% if picture.desc.empty? %>
      <span style="font-style:italic">No description yet.</span>
    <% else %>
      <%= picture.desc %>
    <% end %>
  </p>
  <p class="meta">
    <span class="created">
      <%= picture.created_at.to_s(:pretty) %>
    </span>
    <span class="views">
      <%= picture.views %>
    </span>
  </p>
  <div class="tags">
    <% picture.tags.each do |t| %>
      <%= link_to t, "/pictures/tags/#{t}", :class => "tag" %>
    <% end %> 
  </div>
</div>

app/views/pictures/_votes.erb.html.erb
<div class="votes"> 
  <div class="up">
    <%= link_to "Good feedback", feedback_upvote_path(c), :remote => true, :class => "vote-up-feedback" %>
  </div>
  <div class="count">
    <%= c.votes %>
  </div>
  <div class="down">
    <%= link_to "Bad feedback", feedback_downvote_path(c), :remote => true, :class => "vote-down-feedback" %>
  </div>
</div>

app/views/pictures/_votes.html.erb
<div id="feedback-vote-<%= feedback.id %>" class="votes"> 
  <div class="up">
    <%= link_to "Good feedback", feedback_upvote_path(feedback), :remote => true, :class => "vote-up-feedback" %>
  </div>
  <div class="count">
    <%= feedback.votes %>
  </div>
  <div class="down">
    <%= link_to "Bad feedback", feedback_downvote_path(feedback), :remote => true, :class => "vote-down-feedback" %>
  </div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<% if params[:user_id].nil? %>
  <h1>Latest pictures</h1>
<% else %>
  <% if @pictures.first %>
    <h1><%= @pictures.first.user.username %>'s pictures</h1>
  <% else %>
    <h1> No more pictures found. </h1>
  <% end %>
<% end %>

<div class="pictures">
  <%= render @pictures %>
</div>

<br style="clear: both"/>
<% if @pictures.size == 6 %>
<div class="next">
  <a href="?page=<%= params[:page] ? params[:page].to_i + 1 : 1%>"> more </a>
</div>
<% end %>

app/views/pictures/index.js.erb
$(".pictures").append('<%= escape_javascript(render(@pictures)) %>');
$("#loading").hide().remove();

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<h1>
  <%= @picture.name %>
  <% if current_user && current_user.can_edit?(@picture) %>
    <%= link_to 'Edit Picture', edit_picture_path(@picture), :class => 'edit' %>
  <% end %>
</h1>
<div class="large">
  <%= image_tag @picture.pic.url(:large), :width => "100%"%>
</div>
<div class="picture-content">
  <div class="user">
    <div class="avatar">
      <%= gravatar(@picture.user.email, 50) %>
    </div>
    <div class="username">
      <%= link_to @picture.username, username_profile_path(@picture.username) %>
    </div>
    <div class="description">
      <%= @picture.desc %>
    </div>
  </div>

  <div class="tags">
    Tags: 
  <% @picture.tags.each do |t| %>
    <%= link_to t, "/pictures/tags/#{t}", :class => "tag" %>
  <% end %>
  </div>

  <div class="link-flag">
    <%= link_to "Link", @picture %> | <a href="#"> Flag </a>
  </div>

  <h2> Feedback </h2>
  <div id="comments">
    <%= render @picture.feedbacks.order_by(:votes.desc) %>
  </div>

  <%= render "/feedbacks/form", :picture => @picture %>

</div>