config/routes.rb
Foto::Application.routes.draw do


  resources :tags

  devise_for :users
  
  get "welcome/index"
  get "profile"       => "profiles#user_profile", :as => :user_profile
  get "profile/edit"  => "profiles#edit",         :as => :edit_user_profile
  post"profile/edit"  => "profiles#update"
  get "profiles/:id"  => "profiles#show"
  put "profile"       => "profiles#update"
  
  get "/users/:username" => "profiles#show",       :as => :username_profile
  resources :users do
    resources :pictures
    resources :feedbacks
  end
  
  resources :pictures do
    resources :feedbacks
  end

  match "/pictures/tags/:tag"       => "pictures#tags", :as => :tagged_with
  match "/feedbacks/"               => "feedbacks#index"
  match "/feedbacks/:id/upvote"     => "feedbacks#upvote", :as => :feedback_upvote
  match "/feedbacks/:id/downvote"   => "feedbacks#downvote", :as => :feedback_downvote

  root :to => "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>notebookdrawings.com</title>
  <%= stylesheet_link_tag "screen" %>
  <%= javascript_include_tag "jquery.min", "rails", "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <div class="container">
      <div id="logo">
      	<h1><%= link_to "Notebook Drawings", root_path %></h1>
      </div>
      <div id="nav">
        <%= link_to "Home", root_path %>
        <%= link_to "Tags", tags_path %>
        <%= link_to "Pictures", pictures_path %>

        <% if current_user %>
        <%= link_to "Upload", new_picture_path %>
        <%= link_to "Sign out", destroy_user_session_path %>
        <a href="<%=user_profile_path%>" class="user-profile-link">
          <%= current_user.username %>
          <%= gravatar(current_user.email, 14) %>
        </a>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="main-content" class="container">
		<div class="boxed clearfix">
    	<%= yield %>
		</div>
  </div>
</body>
</html>